### ISSUE TITLE
无法访问此网站

### ISSUE THREAD

**Issue by FTF-git** [yuhaqiang123/my-love#3]
无法访问此网站-无法打开，如：java-线程池内容

**Comment by juejin-wuyang** [comment]
> 无法访问此网站-无法打开，如：java-线程池内容

能贴个连接吗? 我看下

**Comment by FTF-git** [comment]
> > 无法访问此网站-无法打开，如：java-线程池内容
> 
> 能贴个连接吗? 我看下

https://raw.githubusercontent.com/yuhaqiang123/my-love/master/java/%E7%BA%BF%E7%A8%8B%E6%B1%A0%20%E7%9A%84%E5%85%B6%E4%BB%96%E4%BD%BF%E7%94%A8.xmind

**Comment by juejin-wuyang** [comment]
> > > 无法访问此网站-无法打开，如：java-线程池内容
> > 
> > 
> > 能贴个连接吗? 我看下
> 
> https://raw.githubusercontent.com/yuhaqiang123/my-love/master/java/%E7%BA%BF%E7%A8%8B%E6%B1%A0%20%E7%9A%84%E5%85%B6%E4%BB%96%E4%BD%BF%E7%94%A8.xmind

这是个 xmind 格式的文件, 建议使用 xmind8 打开

**Comment by FTF-git** [comment]
> > > > 无法访问此网站-无法打开，如：java-线程池内容
> > > 
> > > 
> > > 能贴个连接吗? 我看下
> > 
> > 
> > https://raw.githubusercontent.com/yuhaqiang123/my-love/master/java/%E7%BA%BF%E7%A8%8B%E6%B1%A0%20%E7%9A%84%E5%85%B6%E4%BB%96%E4%BD%BF%E7%94%A8.xmind
> 
> 这是个 xmind 格式的文件, 建议使用 xmind8 打开

download不行。
raw.githubusercontent.com/yuhaqiang123/my-love/master/java/线程池%20的其他使用.xmind
